---
name: build

on:
  push:
    branches: 
    tags:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build & Test
      run: |
        go get -v
        go test -timeout=60s -race -covermode=atomic -coverprofile=$GITHUB_WORKSPACE/profile.cov
        go build -v -race ./... 

    - name: linter
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest

    - name: install goveralls
      run: GO111MODULE=off go get -u -v github.com/mattn/goveralls

    - name: submit coverage
      run: $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

